### ISSUE TITLE
Can't open the the IP address

### ISSUE THREAD

**Issue by RulinShao** [IntelLabs/VL-InterpreT#4]
Hi, thanks for providing this super cool tool!
I'm trying the example provided on `example_database2` but I never reached the page (showing it took too long to response). Any idea on solving this?

**Comment by RulinShao** [comment]
Hi @meng-du, thanks for the quick reply!!
I'm running on an aws p3 instance with the following command:

> python run_app.py --port 6006 --database example_database2

and I got this output:
<img width="841" alt="Screen Shot 2022-09-29 at 2 08 11 PM" src="https://user-images.githubusercontent.com/61305636/193109831-939fb003-ba3f-4a93-bde3-211574a81da3.png">

I think everything is normal except that I can't reach the link. I'll keep it alive for a while if you would like to check. Thanks a lot!

**Comment by meng-du** [comment]
Got it. If you are running it remotely (on AWS), then you won't be able to visit it through the local link (the IP address is local to your remote server and is not a public link, so that's why you can't visit on your own machine). There are two ways to work around it:
- You may try to run it on your own machine instead of remotely. If you are just testing it out with our example databases, it should work without a GPU or anything fancy.
- If you want to run it on AWS (or any other remote servers), you may want to find a way to forward the port (e.g., port 6006) so that it can be viewed through a public link. In my case, I have been using Kubernetes services and ingresses to do that, but I haven't been using AWS and I'm not quite sure how your instance works (you might want to look for it in AWS documentation). Otherwise, if there is a remote desktop or something available then you'd probably also be able to view it through the browser in the remote desktop.

**Comment by RulinShao** [comment]
Got it! Thanks so much!
